version: '3.4'


networks:
  bridge-net:
    driver: bridge


services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug 
    volumes: 
      - C:\MyData\Redis:/data
    networks:
      - bridge-net


  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - bridge-net


  console-api:
    image: ${REGISTRY:-console}/api:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: HHRU_Console.Api/Dockerfile
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_CONNECTION_STRING=redis:6379
    networks:
      - bridge-net

