version: '3.4'


networks:
  hhru_console:
    external: true



services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:\MyData\MongoDB:/data/db
    networks:
      - hhru_console

  mongo-express:
    image: mongo-express:latest
    container_name: mongodb-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - hhru_console

  console-api:
    image: ${REGISTRY:-console}/api:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "5002:80"
      - "5003:443" 
    build:
      context: .
      dockerfile: HHRU_Console.Api/Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - hhru_console
    volumes:
      - ~/.aspnet/https:/https:ro

