version: '3.4'


networks:
  bridge-net:
    driver: bridge


services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:\MyData\MongoDB:/data/db
    networks:
      - bridge-net

  console-api:
    image: ${REGISTRY:-console}/api:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: HHRU_Console.Api/Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - bridge-net

